// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tascii.Server.Models;

#nullable disable

namespace Tascii.Server.Migrations
{
    [DbContext(typeof(TasciiDBContext))]
    partial class TasciiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tascii.Server.Models.Boards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Board1",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Board2",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Board1",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Board1",
                            OwnerId = 2
                        });
                });

            modelBuilder.Entity("Tascii.Server.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("xCoord")
                        .HasColumnType("int");

                    b.Property<int?>("yCoord")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            content = "Note1 for User1 Board1",
                            xCoord = 10,
                            yCoord = 10
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            content = "Note2 for User1 Board1",
                            xCoord = -10,
                            yCoord = -10
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 2,
                            content = "Note1 for User1 Board2",
                            xCoord = -10,
                            yCoord = -10
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 2,
                            content = "Note2 for User1 Board2",
                            xCoord = 10,
                            yCoord = 10
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 3,
                            content = "Note2 for User2 Board1",
                            xCoord = -10,
                            yCoord = -10
                        },
                        new
                        {
                            Id = 6,
                            BoardId = 3,
                            content = "Note1 for User2 Board1",
                            xCoord = 10,
                            yCoord = 10
                        },
                        new
                        {
                            Id = 7,
                            BoardId = 4,
                            content = "Note2 for User2 Board2",
                            xCoord = -10,
                            yCoord = -10
                        },
                        new
                        {
                            Id = 8,
                            BoardId = 4,
                            content = "Note1 for User2 Board2",
                            xCoord = 10,
                            yCoord = 10
                        });
                });

            modelBuilder.Entity("Tascii.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "user1",
                            Password = "password1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user2",
                            Password = "password2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
